# DROP database IF EXISTS projectDB;

# CREATE DATABASE IF NOT EXISTS projectDB;
#
# USE projectDB;

CREATE TABLE IF NOT EXISTS `SELLER` (
  `SELLER_ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `SURNAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `POSTCODE` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS `BUYER` (
  `BUYER_ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `SURNAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `POSTCODE` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS `PROPERTY` (
  `PROPERTY_ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `POSTCODE` VARCHAR(255) NOT NULL,
  `TYPE` ENUM('DETACHED', 'SEMI', 'APARTMENT') NOT NULL,
  `NUMBER_OF_BEDROOMS` INT(3) NOT NULL,
  `NUMBER_OF_BATHROOMS` INT(3) NOT NULL,
  `GARDEN` BIT NOT NULL,
  `PRICE` DECIMAL(11,2),
  `STATUS` ENUM('FORSALE', 'SOLD', 'WITHDRAWN') NOT NULL,
  `SELLER_ID` INT NOT NULL,
  `BUYER_ID` INT,
  FOREIGN KEY (`SELLER_ID`) REFERENCES SELLER(SELLER_ID),
  FOREIGN KEY (`BUYER_ID`) REFERENCES BUYER(BUYER_ID)
);

CREATE TABLE IF NOT EXISTS `BOOKING` (
  `BOOKING_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `BUYER_ID` INT NOT NULL,
  `PROPERTY_ID` INT NOT NULL,
  `TIME` TIMESTAMP,
  FOREIGN KEY (`BUYER_ID`) REFERENCES BUYER(BUYER_ID),
  FOREIGN KEY (`PROPERTY_ID`) REFERENCES PROPERTY(PROPERTY_ID)
);
