package com.qa.project.persistence.domain;

import java.sql.Timestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/*
 * This class BookingDomain is used to represent an 'booking' record in the database table. 
 * The class is annotated as JPA Entity, which is used to define the mapping between the 
 * class and the database table. The class also has private fields that are annotated 
 * with @Column annotation which is used to map the fields to the corresponding columns 
 * in the table. The field id is annotated with @Id and @GeneratedValue(strategy = GenerationType.IDENTITY) 
 * this is used to indicate that the field is primary key and the value will be generated by the database. 
 */

@Entity
@Table(name = "booking")
public class BookingDomain {
	
	@Id // This sets the variable to be the primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY) // this Auto-Increments for us
	@Column(name = "booking_id") // assign a custom name to the column
	private Long id;
	

	@ManyToOne()
	@JoinColumn(name = "buyer_id")
	private BuyerDomain buyer;
	
	@ManyToOne()
	@JoinColumn(name = "property_id")
	private PropertyDomain property;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time")
	private Timestamp time;
	
	// default constructor
	public BookingDomain() {
		super();
	}
	
	// all arguments constructor
	public BookingDomain(Long id, BuyerDomain buyer, PropertyDomain property, Timestamp time) {
		super();
		this.id = id;
		this.buyer = buyer;
		this.property = property;
		this.time = time;
	}
	
	// getters and setters
	
	public Long getId() {
		return id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	public BuyerDomain getBuyer() {
		return buyer;
	}

	public void setBuyer(BuyerDomain buyer) {
		this.buyer = buyer;
	}

	public PropertyDomain getProperty() {
		return property;
	}

	public void setProperty(PropertyDomain property) {
		this.property = property;
	}

	public Timestamp getTime() {
		return time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}
	
}
